//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories_VW
    {
        public int CategoryID { get; set; }
        public string CategoryType { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string ParentCategory { get; set; }
    }
}
