//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBadge
    {
        public int BadgeID { get; set; }
        public int ClientID { get; set; }
        public byte[] Timestamp { get; set; }
        public string Status { get; set; }
        public DateTime DateEarned { get; set; }
    
        public virtual Badge Badge { get; set; }
        public virtual Client Client { get; set; }
    }
}
